# Generated by Django 3.1.7 on 2021-06-19 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalinfo', '0002_auto_20210619_1519'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sale',
            new_name='Grade',
        ),
    ]
